Update test_create-branch.yml

diff --git a/.github/workflows/test_create-branch.yml b/.github/workflows/test_create-branch.yml
--- a/.github/workflows/test_create-branch.yml
+++ b/.github/workflows/test_create-branch.yml
@@ -12,6 +12,8 @@ jobs:
     steps:
       - name: Checkout main branch
         uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
         
       - name: Create and push new branch from tag name
         env:
@@ -23,3 +25,24 @@ jobs:
           git checkout -b ${BRANCH_NAME}
 
           git push --set-upstream origin ${BRANCH_NAME}
+      - name: Read package.xml and create a new text file
+        id: read_xml
+        run: |
+          XML_FILE_PATH="manifest/package.xml"
+          TEXT_FILE_PATH="./package_copy.txt"
+
+          cat ${XML_FILE_PATH} > ${TEXT_FILE_PATH}
+
+          if [ -f "${TEXT_FILE_PATH}" ]; then
+            echo "::notice file=${TEXT_FILE_PATH}::${TEXT_FILE_PATH} has been created with package.xml content."
+          else
+            echo "::error file=${TEXT_FILE_PATH}::Failed to create ${TEXT_FILE_PATH}."
+            exit 1
+          fi
+      - name: Commit and push the new text file
+        run: |
+          git config user.name 'github-actions[bot]'
+          git config user.email 'github-actions[bot]@users.noreply.github.com'
+          git add .
+          git commit -m "Add package.xml content as a text file" || echo "No changes to commit"
+          git push
